### ISSUE TITLE
Config files problem !

### ISSUE THREAD

**Issue by Bugsoul** [Ben-Kerman/mpv-sub-scripts#18]
I was trying to auto activate sub-skip, when I create a folder (script-opts) and conf file the script didn't work utterly. Could you please check it.

Also, you write "#default_state=no/yes",,, however, in the lua file "false/true". ?

**Comment by Ben-Kerman** [comment]
I just pushed a commit that should fix that issue, try downloading the script again. No idea why I didn't notice it before, maybe something about mpv's behavior changed since I last did any testing

In script config files you have to use `yes`/`no` instead of `true`/`false` because the options script [only recognizes those values](https://github.com/mpv-player/mpv/blob/657fd2804c75fd4c838012ecbf5ce4536e4d487b/player/lua/options.lua#L6) for boolean entries. Using `true` instead is an error and results in the value being set to `nil`
