### ISSUE TITLE
Sub-Skip Keybindings 

### ISSUE THREAD

**Issue by Lucridius** [Ben-Kerman/mpv-sub-scripts#7]
Would you be able to add keybindings so that you can change the lead-in/out times? 
(Having to not ever open the the .lua to alter how you want it to work is just a nice convenience )

**Comment by Ben-Kerman** [comment]
You don't have to open the script, it's already a separate config file. Changing the lead-in/out at runtime would only work for the current mpv instance anyway, so I don't really see that big of a use case for it, honestly.

If you can program feel free to create a pull request, and I'll merge it. Otherwise I might add it myself at some point if I feel like it.

**Comment by Lucridius** [comment]
I can't program haha, but it's not really that big of a deal weather you implement it or not (I just thought it could come in handy)

thanks for getting back to me though 👍 .
